=== zdavatz/elexis/src/ch.elexis/rsc/EMREntry.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated from EMREntry.xml by XMLBuddy -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="EMR">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="record" maxOccurs="unbounded"/>
				<xs:element ref="analyses"/>
				<xs:element ref="document"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:NMTOKEN" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="address">
		<xs:complexType/>
	</xs:element>
	<xs:element name="analyse">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="abnormal" type="xs:boolean" use="required"/>
					<xs:attribute name="date" type="xs:NMTOKEN" use="required"/>
					<xs:attribute name="labEAN" type="xs:integer" use="required"/>
					<xs:attribute name="normRange" type="xs:NMTOKEN"/>
					<xs:attribute name="param" type="xs:string" use="required"/>
					<xs:attribute name="type" type="xs:NMTOKEN" use="required"/>
					<xs:attribute name="unit" type="xs:string"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="analyses">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="analyse" maxOccurs="unbounded"/>
				<xs:element ref="ecg"/>
				<xs:element ref="image" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="document">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="address"/>
				<xs:element ref="text"/>
			</xs:sequence>
			<xs:attribute name="date" type="xs:NMTOKEN" use="required"/>
			<xs:attribute name="imageRef" type="xs:NMTOKEN" use="required"/>
			<xs:attribute name="type" type="xs:NMTOKEN" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="ecg">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="abnormal" type="xs:boolean" use="required"/>
					<xs:attribute name="date" type="xs:NMTOKEN" use="required"/>
					<xs:attribute name="imageRef" type="xs:NMTOKEN" use="required"/>
					<xs:attribute name="labEAN" type="xs:integer" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="image">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="abnormal" type="xs:boolean" use="required"/>
					<xs:attribute name="date" type="xs:NMTOKEN" use="required"/>
					<xs:attribute name="imageRef" type="xs:NMTOKEN" use="required"/>
					<xs:attribute name="type" type="xs:string" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="markup">
		<xs:complexType>
			<xs:attribute name="from" type="xs:integer" use="required"/>
			<xs:attribute name="length" type="xs:integer" use="required"/>
			<xs:attribute name="type" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="record">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="markup"/>
				<xs:element ref="text"/>
				<xs:element ref="xref"/>
			</xs:choice>
			<xs:attribute name="author" type="xs:NMTOKEN" use="required"/>
			<xs:attribute name="date" type="xs:NMTOKEN" use="required"/>
			<xs:attribute name="id" type="xs:NMTOKEN" use="required"/>
			<xs:attribute name="responsibleEAN" type="xs:integer" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="text" type="xs:string"/>
	<xs:element name="xref">
		<xs:complexType>
			<xs:attribute name="from" type="xs:integer" use="required"/>
			<xs:attribute name="id" type="xs:string" use="required"/>
			<xs:attribute name="length" type="xs:integer" use="required"/>
			<xs:attribute name="provider" type="xs:NMTOKEN" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== zdavatz/elexis/src/ch.elexis/rsc/EMREntry.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Ein Beispiel für einen SAMDAS-konformen KG-Eintrag -->
<EMR xmlns:samdas="http://www.elexis.ch/XSD/EMREntry"
	 xsi:noNamespaceSchemaLocation="EMREntry.xsd"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="0abcuuid">
	<record date="2006-08-24" author="gerry" responsibleEAN="0122333" id="0ab12UUID">
		<text>Dies ist ein KG-Eintrag.</text>
		<markup type="bold,underlined" from="5" length="2"/>
		<markup type="italic" from="10" length="5"/>
		<xref provider="ch.elexis:brief" id="Brief#0xddfd" from="7" length="3"/>	
	</record>
	<record date="2006-08-30" author="gerry" responsibleEAN="012333" id="0ab13UUID">
		<text>Heute alles in Butter</text>
		<xref provider="bildanzeige" id="023345354" from="4" length="5"/>
		<xref provider="privatnotizen" id="99882334:3442?" from="10" length="8"/>
	</record>
	<analyses>
		<analyse date="2006-08-24" labEAN="122345" param="Hb" type="number" normRange="10.0-15.0" unit="mmol/l" abnormal="true">
			9.8
		</analyse>
		<analyse date="2006-08-24" labEAN="122345" param="Sputumzytologie" type="text" abnormal="false">Unauffällig</analyse>
		<analyse date="2006-08-24" labEAN="122345" param="HIV suchtest" type="absolute" abnormal="false">negativ</analyse>		
		<ecg date="2006-08-24" labEAN="012333" abnormal="false" imageRef="01xsse34UUID">nc SR, LLT, unauff. de- undRepol.</ecg>
		<image date="2006-08-24" type="Rx Thorax pa und seitlich" abnormal="true" imageRef="01xw3454UUID">Infiltrat li Oberlappen</image>
		<image date="2006-08-24" type="MRI Gehirn" abnormal="false" imageRef="missing">unauffällig</image>
	</analyses>
	<document date="2006-08-24" type="incoming" imageRef="0982423UUID">
		<address></address>
		<text></text>
	</document>
</EMR>
